language: r

## minimal travis config
## https://docs.travis-ci.com/user/languages/r/
## https://towardsdatascience.com/travis-ci-for-r-advanced-guide-719cb2d9e0e5

## no tests, coverage
## check as CRAN

before_install:
  - sudo apt-get update -y 
  - sudo apt-get -y install libglu1-mesa-dev libharfbuzz-dev libfribidi-dev 

script:
  - R CMD build . --compact-vignettes=gs+qpdf
  - R CMD check *tar.gz ## without CRAN check, --as-cran