version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:4.1.2
    environment:
            _R_CHECK_FORCE_SUGGESTS_: false
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: sudo apt-get update -y && sudo apt-get install gdal-bin libgdal-dev  libgeos++-dev libgeos-3.8.0 libgeos-c1v5 libgeos-dev libgeos-doc sqlite3 -y  
      - run:
          name: Install package dependencies
          command: |
            Rscript \
              -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")' \
              -e 'devtools::install_deps(dependencies = NA)'
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check --no-manual *tar.gz
      - store_test_results:
          path: tmp/tests
